{"name": "test_login_incorrectlyexisting_username_and_password", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 == 400\n +  where 200 = <Response [200]>.status_code", "trace": "self = <Server.API.Tests.test_api_signUp.TestLogin_API object at 0x000001E19A871D60>\n\n    @allure.description('Login incorrectly with existing username and password')\n    def test_login_incorrectlyexisting_username_and_password(self):\n        url = SignUpConstants.url\n        data = SignUpConstants.invalid_existing_data\n        res = requests.post(url, json=data)\n        res_data = res.json()\n>       assert res.status_code == 400\nE       assert 200 == 400\nE        +  where 200 = <Response [200]>.status_code\n\ntest_api_signUp.py:53: AssertionError"}, "description": "Login incorrectly with existing username and password", "start": 1675602372200, "stop": 1675602372701, "uuid": "1fa7f09d-208b-444f-aeae-119fbfe717e4", "historyId": "6dba6d6c204f6b69fb7017eae4404c26", "testCaseId": "d6c09a956bad337d0c0e21058f45288b", "fullName": "test_api_signUp.TestLogin_API#test_login_incorrectlyexisting_username_and_password", "labels": [{"name": "suite", "value": "test_api_signUp"}, {"name": "subSuite", "value": "TestLogin_API"}, {"name": "host", "value": "LAPTOP-CFNBSI63"}, {"name": "thread", "value": "6704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api_signUp"}]}