{"name": "test_login_incorrectly_incorrectly_with_invalid_password", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 == 400\n +  where 200 = <Response [200]>.status_code", "trace": "self = <Server.API.Tests.test_api_signUp.TestLogin_API object at 0x000001E19A81BEE0>\n\n    @allure.description('Login incorrectly with invalid password')\n    def test_login_incorrectly_incorrectly_with_invalid_password(self):\n        url = SignUpConstants.url\n        data = SignUpConstants.invalid_data_password\n        res = requests.post(url, json=data)\n        res_data = res.json()\n>       assert res.status_code == 400\nE       assert 200 == 400\nE        +  where 200 = <Response [200]>.status_code\n\ntest_api_signUp.py:43: AssertionError"}, "description": "Login incorrectly with invalid password", "start": 1675602371706, "stop": 1675602372189, "uuid": "72a51dea-d81c-4e16-bdb4-bda78bbc9642", "historyId": "0d1bbdca7c80d7f1d586527f4c1cf510", "testCaseId": "e4340d2a15608fd1db34a53aadda40a0", "fullName": "test_api_signUp.TestLogin_API#test_login_incorrectly_incorrectly_with_invalid_password", "labels": [{"name": "suite", "value": "test_api_signUp"}, {"name": "subSuite", "value": "TestLogin_API"}, {"name": "host", "value": "LAPTOP-CFNBSI63"}, {"name": "thread", "value": "6704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api_signUp"}]}