{"name": "test_login_incorrectly_with_both_invalid_ccredintials", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 == 400\n +  where 200 = <Response [200]>.status_code", "trace": "self = <Server.API.Tests.test_api_login.TestLogin_API object at 0x000001E19A8641C0>\n\n    @allure.description('Login incorrectly with both invalid credintials')\n    def test_login_incorrectly_with_both_invalid_ccredintials(self):\n        url = LoginConstants.url\n        data = LoginConstants.invalid_both_data\n        res = requests.post(url, json=data)\n        res_data = res.json()\n>       assert res.status_code == 400\nE       assert 200 == 400\nE        +  where 200 = <Response [200]>.status_code\n\ntest_api_login.py:23: AssertionError"}, "description": "Login incorrectly with both invalid credintials", "start": 1675602368199, "stop": 1675602368807, "uuid": "cba2cc83-1433-4bc1-901c-7892f5ea1693", "historyId": "b31e49c8ec639788607f078df12a6dc2", "testCaseId": "92b15b6ea2b6d4e6d5abc15616a73e4d", "fullName": "test_api_login.TestLogin_API#test_login_incorrectly_with_both_invalid_ccredintials", "labels": [{"name": "suite", "value": "test_api_login"}, {"name": "subSuite", "value": "TestLogin_API"}, {"name": "host", "value": "LAPTOP-CFNBSI63"}, {"name": "thread", "value": "6704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api_login"}]}