{"name": "test_login_incorrectly_with_invalid_username", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 == 400\n +  where 200 = <Response [200]>.status_code", "trace": "self = <Server.API.Tests.test_api_login.TestLogin_API object at 0x000001E19A8713D0>\n\n    @allure.description('Login incorrectly with invalid username')\n    def test_login_incorrectly_with_invalid_username(self):\n        url = LoginConstants.url\n        data = LoginConstants.invalid_data_username\n        res = requests.post(url, json=data)\n        res_data = res.json()\n>       assert res.status_code == 400\nE       assert 200 == 400\nE        +  where 200 = <Response [200]>.status_code\n\ntest_api_login.py:33: AssertionError"}, "description": "Login incorrectly with invalid username", "start": 1675602368858, "stop": 1675602369338, "uuid": "b9e973cf-ed87-45da-b2f0-77c5d075e085", "historyId": "fc863867798e80dbe2ea69f6788cfc59", "testCaseId": "dcf53a0146abe053eb0a1b4d30d7a6be", "fullName": "test_api_login.TestLogin_API#test_login_incorrectly_with_invalid_username", "labels": [{"name": "suite", "value": "test_api_login"}, {"name": "subSuite", "value": "TestLogin_API"}, {"name": "host", "value": "LAPTOP-CFNBSI63"}, {"name": "thread", "value": "6704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api_login"}]}